name: Test Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted
    env:
      MESSAGE: "fsuifo ujsrdilguseirgrsieuguidhgiurhtiughrtiugbhurih"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo $MESSAGE
